### ISSUE TITLE
LDVMi not running as background process

### ISSUE THREAD

**Issue by jakubklimek** [ldvm/LDVMi#101]
When trying to run activator run with nohup, I get:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/.ivy2/cache/ch.qos.logback/logback-classic/jars/logback-classic-1.1.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/.ivy2/cache/org.slf4j/slf4j-log4j12/jars/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
^[[35m--- (Running the application, auto-reloading is enabled) ---^[[0m

[^[[37minfo^[[0m] play - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

^[[32m(Server started, use Ctrl+D to stop and go back to the console...)^[[0m

java.io.IOException: Bad file descriptor
        at java.io.FileInputStream.read0(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:207)
        at jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:248)
        at jline.internal.InputStreamReader.read(InputStreamReader.java:261)
        at jline.internal.InputStreamReader.read(InputStreamReader.java:198)
        at jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2038)
        at play.PlayConsoleInteractionMode$$anonfun$waitForKey$1.play$PlayConsoleInteractionMode$$anonfun$$waitEOF$1(PlayInteractionMode.scala:62)
        at play.PlayConsoleInteractionMode$$anonfun$waitForKey$1$$anonfun$apply$1.apply$mcV$sp(PlayInteractionMode.scala:73)
        at play.PlayConsoleInteractionMode$$anonfun$doWithoutEcho$1.apply(PlayInteractionMode.scala:80)
        at play.PlayConsoleInteractionMode$$anonfun$doWithoutEcho$1.apply(PlayInteractionMode.scala:77)
        at play.PlayConsoleInteractionMode$.withConsoleReader(PlayInteractionMode.scala:57)
        at play.PlayConsoleInteractionMode$.doWithoutEcho(PlayInteractionMode.scala:77)
        at play.PlayConsoleInteractionMode$$anonfun$waitForKey$1.apply(PlayInteractionMode.scala:73)
        at play.PlayConsoleInteractionMode$$anonfun$waitForKey$1.apply(PlayInteractionMode.scala:60)
        at play.PlayConsoleInteractionMode$.withConsoleReader(PlayInteractionMode.scala:57)
        at play.PlayConsoleInteractionMode$.waitForKey(PlayInteractionMode.scala:60)
        at play.PlayConsoleInteractionMode$.waitForCancel(PlayInteractionMode.scala:83)
        at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:148)
        at play.PlayRun$$anonfun$playRunTask$1$$anonfun$apply$2$$anonfun$apply$3.apply(PlayRun.scala:96)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)

```

**Comment by jirihelmich** [comment]
Well, I'm sorry, but there's nothing I could do. That's either bug in Activator or Play Framework. Upgrade to latest Play won't be done with LDVMi.

I can show you, how to build WAR with activator and load it into Tomcat.

RW: http://stackoverflow.com/questions/10729443/scala-start-play-server-in-production

**Comment by jirihelmich** [comment]
This is the most preferable way: http://stackoverflow.com/a/25852899/643497
